const mongoose = require("mongoose");

const userSchema = new mongoose.Schema(
  {
    username: { type: String, unique: true },
    email: { type: String, required: true, unique: true },
    fullName: { type: String, required: true },
    passwordHash: { type: String, required: true },
    roleID: {
      type: String,
      enum: ["Student", "Academia", "Industry Official", "Admin"],
      required: true,
    },
    institute: {
      type: String,
      enum: [
        // 🎓 UNIVERSITIES
        "National University of Sciences and Technology (Islamabad)",
        "Bahria University (Islamabad)",
        "Bahria University (Karachi)",
        "Bahria University (Lahore)",
        "COMSATS University (Islamabad)",
        "FAST National University of Computer and Emerging Sciences (Lahore)",
        "FAST National University of Computer and Emerging Sciences (Karachi)",
        "FAST National University of Computer and Emerging Sciences (Islamabad)",
        "FAST National University of Computer and Emerging Sciences (Peshawar)",
        "University of the Punjab (Lahore)",
        "Lahore University of Management Sciences (Lahore)",
        "Institute of Business Administration (Karachi)",
        "NED University of Engineering and Technology (Karachi)",
        "University of Karachi (Karachi)",
        "Ghulam Ishaq Khan Institute (Topi)",
        "Air University (Islamabad)",
        "Quaid-e-Azam University (Islamabad)",
        "University of Engineering and Technology (Lahore)",
        "Riphah International University (Islamabad)",
        "Sindh Madressatul Islam University (Karachi)",
        "University of Central Punjab (Lahore)",
        "Superior University (Lahore)",
        "Hamdard University (Karachi)",
        "Islamia University of Bahawalpur (Bahawalpur)",
        "University of Management and Technology (Lahore)",
        "Karachi Institute of Economics and Technology (Karachi)",
        "Muhammad Ali Jinnah University (Karachi)",
        "Institute of Space Technology (Islamabad)",
        "National Textile University (Faisalabad)",
        "University of Peshawar (Peshawar)",
        "Balochistan University of IT, Engineering and Management Sciences (Quetta)",
        "Sukkur IBA University (Sukkur)",
        "Virtual University of Pakistan (Lahore)",
        "Preston University (Islamabad)",
        "SZABIST (Karachi)",
        "SZABIST (Islamabad)",
        "SZABIST (Larkana)",

        // 💻 TECH & SOFTWARE COMPANIES
        "Systems Limited (Lahore)",
        "NETSOL Technologies (Lahore)",
        "10Pearls (Karachi)",
        "Arbisoft (Lahore)",
        "TRG Pakistan (Karachi)",
        "CureMD (Lahore)",
        "TPS Pakistan (Karachi)",
        "Techlogix (Lahore)",
        "Afiniti (Islamabad)",
        "Folio3 (Karachi)",
        "VentureDive (Karachi)",
        "Cubix (Karachi)",
        "Ibex Global (Karachi)",
        "Qbatch (Faisalabad)",
        "DevBatch (Lahore)",
        "Ovex Technologies (Islamabad)",
        "KalSoft (Karachi)",
        "Gaditek (Karachi)",
        "Tkxel (Lahore)",
        "NorthBay Solutions (Lahore)",
        "Conrad Labs (Lahore)",
        "Tintash (Lahore)",
        "Mindstorm Studios (Lahore)",
        "Emumba (Islamabad)",
        "Codematics (Abbottabad)",
        "Sofizar (Lahore)",

        // 🏢 GOVERNMENT & PUBLIC SECTOR
        "Pakistan Software Export Board (Islamabad)",
        "Ignite National Technology Fund (Islamabad)",
        "Higher Education Commission (Islamabad)",
        "Pakistan Telecommunication Authority (Islamabad)",
        "National IT Board (Islamabad)",
        "Ministry of IT and Telecommunication (Islamabad)",
        "Pakistan Atomic Energy Commission (Islamabad)",
        "Pakistan Council of Scientific and Industrial Research (Islamabad)",
        "National Engineering and Scientific Commission (Islamabad)",
        "National Incubation Center (Islamabad)",
        "National Incubation Center (Lahore)",
        "National Incubation Center (Karachi)",
        "National Incubation Center (Peshawar)",
        "National Incubation Center (Quetta)",
        "SUPARCO (Karachi)",
        "Pakistan Agricultural Research Council (Islamabad)",
        "Pakistan Council of Renewable Energy Technologies (Islamabad)",
        "Ministry of Science and Technology (Islamabad)",
        "Pakistan Standards and Quality Control Authority (Karachi)",

        // 🔬 RESEARCH & INNOVATION CENTERS
        "National Center for Artificial Intelligence (Islamabad)",
        "National Center for Robotics and Automation (Islamabad)",
        "National Center for Cyber Security (Islamabad)",
        "National Center for Big Data and Cloud Computing (Lahore)",
        "Plan9 Incubator – PITB (Lahore)",
        "NIC Karachi (Karachi)",
        "NIC Lahore (Lahore)",
        "NIC Islamabad (Islamabad)",
        "Center for Advanced Research in Engineering (Islamabad)",
        "Pak-Austria Fachhochschule Institute of Applied Sciences and Technology (Haripur)",

        // 🏭 INDUSTRIAL & CORPORATE SECTOR
        "Engro Corporation (Karachi)",
        "Lucky Cement (Karachi)",
        "Fauji Fertilizer Company (Rawalpindi)",
        "Descon Engineering (Lahore)",
        "Telenor Pakistan (Islamabad)",
        "Jazz (Islamabad)",
        "Zong 4G (Islamabad)",
        "Ufone (Islamabad)",
        "PTCL (Islamabad)",
        "Unilever Pakistan (Karachi)",
        "Nestlé Pakistan (Lahore)",
        "Packages Ltd. (Lahore)",
        "Millat Tractors (Lahore)",
        "Atlas Honda (Karachi)",
        "Pakistan Petroleum Limited (Karachi)",
        "Pakistan State Oil (Karachi)",
        "Habib Bank Limited (Karachi)",
        "Meezan Bank (Karachi)",
        "Allied Bank Limited (Lahore)",
        "MCB Bank (Lahore)",
        "Askari Bank (Rawalpindi)",
        "Engro Foods (Karachi)",
        "K-Electric (Karachi)",
        "Dawlance (Karachi)",
        "Toyota Indus Motors (Karachi)",
        "Honda Atlas Cars (Lahore)",
        "Nishat Mills Limited (Lahore)",
        "Gul Ahmed Textile Mills (Karachi)",
        "Sapphire Group (Lahore)",
        "Coca-Cola Beverages Pakistan (Lahore)",
        "PepsiCo Pakistan (Lahore)",

        // ➕ OTHER OPTION
        "Other",
      ],
      required: true,
    },
    isRemembered: { type: Boolean, default: false },
    resetToken: { type: String },
    resetTokenExpiry: { type: Date },

    // 🚀 New fields for suspension/restriction/limitation
    status: {
      type: String,
      enum: ["active", "suspended", "restricted", "limited"],
      default: "active",
    },
    actionBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" }, // admin who performed action
    actionAt: { type: Date },

    // ✅ New field for student role-based access
    profileCompleted: { type: Boolean, default: false },

    // 🔗 Email activation fields
    isActivated: { type: Boolean, default: false },
    activationToken: { type: String },
    activationExpires: { type: Date },
  },
  { timestamps: true, versionKey: false }
);

module.exports = mongoose.model("User", userSchema);
